server:
  port: 3000

netty:
  host: 127.0.0.1
  port: 9090

# 禁用缓存
spring:
  thymeleaf:
    cache: false
  dubbo:
    protocol:
      port: 20880
      name: dubbo
    application:
      name: hello-world-app
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.xiaoping.service
# 配置 Dubbo
dubbo:
  protocol:
    prot: 20880
    name: dubbo
  application:
    name: hello-world-app
  registry:
    address: zookeeper://127.0.0.1:2181
  scan: com.xiaoping.service