server:
  port: 3000

netty:
  host: 127.0.0.1
  port: 9090

upload:
  rootpath: upload-dir

# 禁用缓存
spring:
  # 配置 thymeleaf 在开发环境禁用缓存
  thymeleaf:
    cache: false
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mbs
    username: root
    password: 123789
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true

