server:
  port: 3000

netty:
  host: 127.0.0.1
  port: 9090

upload:
  rootpath: upload-dir

# 禁用缓存
spring:
  # 配置 thymeleaf 在开发环境禁用缓存
  thymeleaf:
    cache: false
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/school
    username: root
    password: ping1234
    driver-class-name: com.mysql.jdbc.Driver
    # 配置数据库连接池
    druid:
      initial-size: 50
      max-active: 1000
      min-idle: 50
      max-wait: 60000
  jpa:
    database: MYSQL
    show-sql: true

# info 配置项（/actuator/info）
info:
  author: xiaop1ng
  email: jianchaoping@gmail.com
  version: 1.0.0

# 配置 actuator 加载所有的端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
